### ISSUE TITLE
builds for pypy and pypy3 fail

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zc.set#3]
https://travis-ci.org/github/zopefoundation/zc.set/jobs/665761717

**Comment by mgedmin** [comment]
I would be tempted to drop PyPy support, until somebody comes up with a PR to fix these.

**Comment by jamadden** [comment]
On it.

**Comment by mgedmin** [comment]
Looking at the failures I'm wondering if this isn't a bug/incompatibility in PyPy itself?

**Comment by jamadden** [comment]
AFAICS, the language spec doesn't require `set` to implement the reversed versions of the operators. The only documented operators all have `set` as the left-hand argument. That said, PyPy 7.3 did add them.

**Comment by mgedmin** [comment]
According to https://docs.travis-ci.com/user/languages/python/#python-versions the latest PyPy version available on Travis is 7.2 (with `dist: bionic` aka 18.04).  `dist: xenial` is stuck on 7.1.1, and `dist: focal` doesn't have pypy at all.

**Comment by jugmac00** [comment]
I wonder if anybody is running Zope packages on pypy... I never saw anybody filing an issue.

I only see occasional errors on Travis which Jason has to fix as obviously you have to have a very deep implementation knowledge of both cpython and pypy. shrug

**Comment by jamadden** [comment]
My organization is, at least a bit. We're intending to do so more. 

If they're not, more people should: PyPy is often massively faster while using less memory than CPython.
